/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.skagedal.javaaoc.aoc;

public class App {
    public static void main(String[] args) {
        System.out.println("Run the test suite instead, it's more interesting.");
    }
}
