/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.skagedal.javaaoc.aoc;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

@Component
public class App {
    private final List<Object> aocDays;

    public App(ApplicationContext context) {
        this.aocDays = new ArrayList<>(context.getBeansWithAnnotation(AdventOfCode.class).values());
    }

    public void runAllDays() {
        aocDays
            .stream()
            .sorted(Comparator.comparing(day -> day.getClass().getName()))
            .forEach(this::runDay);
    }

    private void runDay(Object aocDay) {
        final var klass = aocDay.getClass();
        System.out.println("Day: " + klass.getName());
        Arrays
            .stream(klass.getDeclaredMethods())
            .filter(method -> method.getName().matches("part[1-9]"))
            .sorted(Comparator.comparing(Method::getName))
            .forEach(method -> {
                try {
                    final var response = method.invoke(aocDay);
                    System.out.printf("Response for %s: %s\n", method.getName(), response);
                } catch (IllegalAccessException | InvocationTargetException e) {
                    System.err.println("ERROR invoking " + method.getName() + " for " + klass.getName());
                }
            });
    }
}
